-- MySQL Script generated by MySQL Workbench
-- Mon Apr 20 23:02:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cul_dampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cul_dampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cul_dampolla` DEFAULT CHARACTER SET utf8 ;
USE `cul_dampolla` ;

-- -----------------------------------------------------
-- Table `cul_dampolla`.`Provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`Provider` (
  `idProvider` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `fax` INT NOT NULL,
  `nif` INT NOT NULL,
  PRIMARY KEY (`idProvider`),
  UNIQUE INDEX `idProvider_UNIQUE` (`idProvider` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`Brand` (
  `idBrand` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Provider_idProvider` INT NOT NULL,
  PRIMARY KEY (`idBrand`),
  UNIQUE INDEX `idBrand_UNIQUE` (`idBrand` ASC) VISIBLE,
  INDEX `fk_Brand_Provider1_idx` (`Provider_idProvider` ASC) VISIBLE,
  CONSTRAINT `fk_Brand_Provider1`
    FOREIGN KEY (`Provider_idProvider`)
    REFERENCES `cul_dampolla`.`Provider` (`idProvider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`Glasses` (
  `idGlasses` INT NOT NULL,
  `prescriptionLeft` VARCHAR(45) NOT NULL,
  `prescriptionRight` VARCHAR(45) NOT NULL,
  `frameType` VARCHAR(45) NOT NULL,
  `frameColor` VARCHAR(45) NOT NULL,
  `colorLeftLense` VARCHAR(45) NOT NULL,
  `colorRightLense` VARCHAR(45) NULL,
  `price` VARCHAR(45) NOT NULL,
  `Brand_idBrand` INT NOT NULL,
  PRIMARY KEY (`idGlasses`),
  UNIQUE INDEX `idGlasses_UNIQUE` (`idGlasses` ASC) VISIBLE,
  INDEX `fk_Glasses_Brand_idx` (`Brand_idBrand` ASC) VISIBLE,
  CONSTRAINT `fk_Glasses_Brand`
    FOREIGN KEY (`Brand_idBrand`)
    REFERENCES `cul_dampolla`.`Brand` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`address` (
  `idAddress` INT NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `floor` INT NOT NULL,
  `door` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `postalCode` INT NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAddress`),
  UNIQUE INDEX `idAddress_UNIQUE` (`idAddress` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`Client` (
  `idClient` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `registerDate` DATETIME NOT NULL,
  `recomendedBy_idClient` INT NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idclient_UNIQUE` (`idClient` ASC) VISIBLE,
  INDEX `fk_client_client1_idx` (`recomendedBy_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_client_client1`
    FOREIGN KEY (`recomendedBy_idClient`)
    REFERENCES `cul_dampolla`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`Sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`Sale` (
  `idSale` INT NOT NULL,
  `employee` VARCHAR(45) NOT NULL,
  `Glasses_idGlasses` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  PRIMARY KEY (`idSale`),
  UNIQUE INDEX `idSale_UNIQUE` (`idSale` ASC) VISIBLE,
  INDEX `fk_Sale_Glasses1_idx` (`Glasses_idGlasses` ASC) VISIBLE,
  INDEX `fk_Sale_Client1_idx` (`Client_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Sale_Glasses1`
    FOREIGN KEY (`Glasses_idGlasses`)
    REFERENCES `cul_dampolla`.`Glasses` (`idGlasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sale_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `cul_dampolla`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`Provider_has_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`Provider_has_address` (
  `idProvider_has_address` INT NOT NULL,
  `address_idAddress` INT NOT NULL,
  `Provider_idProvider` INT NOT NULL,
  PRIMARY KEY (`idProvider_has_address`),
  UNIQUE INDEX `idProvider_has_address_UNIQUE` (`idProvider_has_address` ASC) VISIBLE,
  INDEX `fk_Provider_has_address_address1_idx` (`address_idAddress` ASC) VISIBLE,
  INDEX `fk_Provider_has_address_Provider1_idx` (`Provider_idProvider` ASC) VISIBLE,
  CONSTRAINT `fk_Provider_has_address_address1`
    FOREIGN KEY (`address_idAddress`)
    REFERENCES `cul_dampolla`.`address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Provider_has_address_Provider1`
    FOREIGN KEY (`Provider_idProvider`)
    REFERENCES `cul_dampolla`.`Provider` (`idProvider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cul_dampolla`.`Client_has_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_dampolla`.`Client_has_address` (
  `idClient_has_address` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  `address_idAddress` INT NOT NULL,
  PRIMARY KEY (`idClient_has_address`),
  UNIQUE INDEX `idClient_has_address_UNIQUE` (`idClient_has_address` ASC) VISIBLE,
  INDEX `fk_Client_has_address_Client1_idx` (`Client_idClient` ASC) VISIBLE,
  INDEX `fk_Client_has_address_address1_idx` (`address_idAddress` ASC) VISIBLE,
  CONSTRAINT `fk_Client_has_address_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `cul_dampolla`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_address_address1`
    FOREIGN KEY (`address_idAddress`)
    REFERENCES `cul_dampolla`.`address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
